# Generated by Django 4.2.2 on 2023-06-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Поля сотрудников', 'verbose_name_plural': 'Поля сотрудников'},
        ),
    ]
