# Generated by Django 4.2.2 on 2023-06-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customerprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.TextField(blank=True, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=50000, help_text='в рублях', null=True, verbose_name='Зарплата'),
        ),
    ]
