# Generated by Django 4.2.2 on 2023-06-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=512, verbose_name='Название')),
                ('model', models.TextField(max_length=512, verbose_name='Модель')),
                ('serial_number', models.TextField(max_length=512, verbose_name='Серийный номер')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
                ('warranty_expiration_date', models.DateField(verbose_name='Дата окончания гарантии')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
    ]
