# Generated by Django 4.2.2 on 2023-06-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_spare_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Укажите цену в рублях', max_digits=10, verbose_name='Цена'),
        ),
    ]
