# Generated by Django 4.2.2 on 2023-06-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='в рублях', max_digits=10, verbose_name='Цена'),
        ),
    ]
