# Generated by Django 4.2.2 on 2023-07-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='datetime_finished',
            field=models.DateTimeField(verbose_name='Дата окончания гарантии'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='datetime_started',
            field=models.DateTimeField(verbose_name='Дата начала гарантии'),
        ),
    ]
