# Generated by Django 4.2.1 on 2023-11-16 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0006_historicaldevice'),
        ('guarantees', '0002_alter_guarantee_datetime_finished_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGuarantee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('datetime_started', models.DateTimeField(verbose_name='Дата начала гарантии')),
                ('datetime_finished', models.DateTimeField(verbose_name='Дата окончания гарантии')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Активна'), (1, 'Просрочена'), (2, 'Использована')], default=0, verbose_name='Статус')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.device', verbose_name='Устройство')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Гарантия',
                'verbose_name_plural': 'historical Гарантии',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
